CREATE TABLE PRODUCT (
	PRODUCT_id VARCHAR2(20),
	PRODUCT_name VARCHAR2(20),
	PRICE NUMBER,
    PRIMARY KEY (PRODUCT_id),
);
CREATE TABLE COSTUMER (
	COSTUMER_id VARCHAR2(20),
	COSTUMER_name VARCHAR2(20),
	COSTUMER_tel NUMBER,
    PRIMARY KEY (COSTUMER_id),

);
CREATE TABLE ORDERS (
	COSTUMER_id VARCHAR2(20),
	PRODUCT_id VARCHAR2(20),
	QUANTITY NUMBER,
    TOTAL_amount NUMBER,
    FOREIGN KEY (COSTUMER_id) REFERENCES COSTUMER(COSTUMER_id),
    FOREIGN KEY (PRODUCT_id) REFERENCES PRODUCT(PRODUCT_id),

);
Alter Table PRODUCT ADD CONSTRAINT pk_PRODUCT PRIMARY KEY(category);
Alter Table ORDERS ADD CONSTRAINT pk_ORDERS PRIMARY KEY(OrderDate) DEFAULT SYSDATE;
